name: RelayEscapePlugin
main: com.wbm.plugin.Main
version: 1.0
description: worldbiomusic (discord -> worldbiomusic#7075)

commands:
  re:
    description: relay escaper plugin command
    usage:  |  
          =========Command=========
          /re tutorial
          /re goods
          /re room [load | title] <title>
          /re room [empty | list | finish]
          /re minigame [ok | kick] <player>
          /re minigame waitlist
      
permissions:
  re.*:
    description: super permission
    default: op

  re.admin:
    description: admin permission
    
  re.user:
    description: general player
    default: true


























